# -*- coding: utf-8 -*-
"""asistente_de_recetas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNyE2V71mM78ks_rMy43MgRtBF6aSjuC
"""

import json
from sys import displayhook
from googletrans import Translator
from gtts import gTTS
from IPython.display import Audio

print("Bienvenido soy tu asistente de recetas.")

class AsistenteRecetas:

    def __init__(self):
        self.idioma = {'español': 'es', 'inglés': 'en'}
        self.idioma_elegido = self.elegir_idioma()
        self.recetas = self.carga_json()
        self.ingredientes_usuario = []
        self.translator = Translator()

    def elegir_idioma(self):
        while True:
            language = input("Seleccione el idioma (español / inglés): ").lower()
            if language in self.idioma:
                return language
            print("Por favor, seleccione un idioma válido.")

    def traducir(self, text):
        idioma_destino = self.idioma.get(self.idioma_elegido)
        return self.translator.translate(text, dest=idioma_destino).text if idioma_destino else text

    def carga_json(self):
        with open(f"recetas_{self.idioma[self.idioma_elegido]}.json", 'r') as archivo:
            return json.load(archivo)

    def hablar(self, texto):
        texto = texto.replace('_', ' ')
        tts = gTTS(text=texto, lang=self.idioma[self.idioma_elegido])
        tts.save("respuesta.mp3")
        return Audio("respuesta.mp3", autoplay=True)

    def buscar_recetas(self):
        while True:
            if not self.ingredientes_usuario:
                self.ingredientes_usuario = input(self.traducir("Ingrese los ingredientes que tiene: ")).replace(' y ', ', ').replace(' and ', ', ').split(',')
                self.ingredientes_usuario = [ingrediente.strip().lower() for ingrediente in self.ingredientes_usuario]

            recetas_posibles = [receta.get('nombre' if self.idioma_elegido == 'español' else 'name', 'Nombre no disponible') for receta in self.recetas if all(ingrediente.lower() in map(str.lower, receta.get('ingredientes' if self.idioma_elegido == 'español' else 'ingredients', [])) for ingrediente in self.ingredientes_usuario)]

            if recetas_posibles:
                mensaje = self.traducir("Puedes realizar las siguientes recetas:\n ") + '\n'.join(f'- {receta}' for receta in recetas_posibles)
                print(mensaje)
                displayhook(self.hablar(mensaje))
                while True:
                    nombre_receta = input(self.traducir("\nIntroduzca el nombre de la receta que quiere ver: ")).lower().replace(' ', '_')
                    if nombre_receta in ['exit', 'salir']:
                        return
                    elif nombre_receta in map(str.lower, recetas_posibles):
                        self.mostrar_receta(nombre_receta)
                        break
                    print(self.traducir("Nombre de receta no válido o no encontrado."))

                if not self.preguntar_otra_receta():
                    return
            else:
                print(self.traducir("No hay recetas disponibles con los ingredientes proporcionados."))
                self.ingredientes_usuario = None

    def mostrar_receta(self, nombre_receta):
        receta_encontrada = next((receta for receta in self.recetas if receta.get('nombre' if self.idioma_elegido == 'español' else 'name', '').lower() == nombre_receta), None)

        if receta_encontrada:
            print(self.traducir("\nIngredientes:"))
            print('\n'.join(f"{i}. {ingrediente}" for i, ingrediente in enumerate(receta_encontrada.get('ingredientes' if self.idioma_elegido == 'español' else 'ingredients', []), 1)))
            print(self.traducir("\nPasos:"))
            print('\n'.join(f"{i}. {paso}" for i, paso in enumerate(receta_encontrada.get('pasos' if self.idioma_elegido == 'español' else 'steps', ['Receta no disponible']), 1)))
        else:
            print(self.traducir("Receta no encontrada."))

    def preguntar_otra_receta(self):
        respuesta = input(self.traducir("\n¿Desea ver otra receta de la lista?: ")).lower()
        if respuesta.startswith('s') or respuesta.startswith('y'):
            return True
        elif respuesta.startswith('n'):
            respuesta_nueva = input(self.traducir("\n¿Desea ver una receta con otros ingredientes?: ")).lower()
            if respuesta_nueva.startswith('s') or respuesta_nueva.startswith('y'):
                self.ingredientes_usuario.clear()
                return True
            elif respuesta_nueva.startswith('n'):
                print(self.traducir("Espero haberle sido de ayuda, ¡Hasta luego! 😊"))
                return False
        else:
            print(self.traducir("Respuesta no válida."))
            return True


# Ejemplo de uso
asistente = AsistenteRecetas()
asistente.buscar_recetas()